# Generated by Django 3.2.7 on 2021-10-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tel',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
