# Generated by Django 3.2.7 on 2021-10-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0002_auto_20211003_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='celular',
            field=models.CharField(default='11111111111', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
