# Generated by Django 3.2.7 on 2021-10-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0003_auto_20211004_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='chave',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='necessidade',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='qual_deficiencia',
            field=models.CharField(max_length=600),
        ),
    ]
