# Generated by Django 3.2.7 on 2021-10-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0004_auto_20211008_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='chave',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
