# Generated by Django 3.2.7 on 2021-10-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0005_alter_candidato_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4'),
            preserve_default=False,
        ),
    ]
